### ISSUE TITLE
Benchmarks Tesing with K8s Slave pods

### ISSUE THREAD

**Issue by subinmt** [kubernauts/jmeter-kubernetes#10]
@infinitydon , I have a requirement, raise 200k connections in 5min and send events to my environments. How can I check this Benchmark testing. How many slave pods I need to launch for generating 200k and send events.

**Comment by infinitydon** [comment]
Hi subinmt,

Capacity dimensioning can be a bit tricky, it depends on the kind of tests, a general rule form jmeter is:

A single JMeter client running on a 2-3 GHz CPU (recent CPU) can handle 1000-2000 threads depending on the type of test.

So if you are having 200k threads, then by default using the CPU shown above you will need around 100 slave nodes. You may be able to use some lower number of nodes with higher number of threads per node but it all depends on the actual kind of tests you want to perform.

Reference:

https://jmeter.apache.org/usermanual/jmeter_distributed_testing_step_by_step.html
