### ISSUE TITLE
Source of plugins folder

### ISSUE THREAD

**Issue by erkanerol** [kubernauts/jmeter-kubernetes#11]
In the dockerfile of base image, there is such a line:
`ADD jmeter-plugins/lib /jmeter/apache-jmeter-$JMETER_VERSION/lib`

What is the content of the `jmeter-plugins/lib` folder? I can see the content in the docker image but I don't know from where I can download. I want to make the docker build process reproducible.

**Comment by infinitydon** [comment]
Hi erkanerol,

You can find the plugins via:

https://github.com/kubernauts/jmeter-kubernetes/tree/master/plugins

**Comment by erkanerol** [comment]
Hi,

The content of "bzm-parallel-0.4.zip" exist in the docker image but I cannot see the content of "JMeterPlugins-Standard-1.4.0.zip" in the docker image. Am I wrong?

**Comment by infinitydon** [comment]
Hi,

You can download it via the jmeter website

https://jmeter-plugins.org/downloads/file/JMeterPlugins-Standard-1.4.0.zip

**Comment by erkanerol** [comment]
Sorry. Maybe I couldn't express myself properly. I am trying to automate the docker build process. When I run the docker image and run "ls" command, I can see the content of the "bzm-parallel-0.4.zip" in the image. However, I couldn't find the content of "JMeterPlugins-Standard-1.4.0.zip". I believe you didn't use the second zip file during building "kubernautslabs/jmeter_base" image.

**Comment by infinitydon** [comment]
Are you still having this issue? Please re-open if it is not solved yet.
