### ISSUE TITLE
master gui

### ISSUE THREAD

**Issue by KennethNagin** [kubernauts/jmeter-kubernetes#18]
I would like to use the jmeter GUI to create my own master plans. How would you expose the master's gui in the cluster created by your scripts?

**Comment by infinitydon** [comment]
Hi,

You should run the jmeter GUI mode on your system, it is designed to be run as a desktop APP and not to be run within the cluster.

After creating/editing your test script using the GUI, you can then use it for the load testing in the kubernetes cluster..

I hope this addresses your question.
