### ISSUE TITLE
chmod: changing permissions of '/root/load_test': Read-only file system

### ISSUE THREAD

**Issue by ghost** [kubernauts/jmeter-kubernetes#2]
Following the steps from here: https://blog.kubernauts.io/load-testing-as-a-service-with-jmeter-on-kubernetes-fc5288bb0c8b

While launching the dashboard script...

$ ./dashboard.sh
Creating Influxdb jmeter Database
Creating the Influxdb data source
**chmod: changing permissions of '/root/load_test': Read-only file system**
**command terminated with exit code 1**
{"datasource":{"id":1,"orgId":1,"name":"jmeterdb","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://jmeter-influxdb:8086","password":"admin","user":"admin","database":"jmeter","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"jmeterdb"}

$ kubelet --version
Kubernetes v1.9.6

It's not possible to run the tests.

**Comment by arashkaffamanesh** [comment]
It seems to be related with this critical issue:
https://github.com/kubernetes/kubernetes/issues/61563
https://github.com/kubernetes/kubernetes/issues/61178

It works with k8s 1.9.0 ( - 1.9.2 ??)

P.S.: with k8s 1.9.4 I'm getting:
CreateContainerConfigError
for jmeter-master pod:

(⎈ |minikube:ltaas)]$ k get pods
NAME                               READY     STATUS                       RESTARTS   AGE
influxdb-jmeter-5cbd7b8469-x2d88   1/1       Running                      0          14s
jmeter-grafana-65dd5f6b79-vgtfw    1/1       Running                      0          14s
jmeter-master-75f66dbb5f-p7tv5     0/1       **CreateContainerConfigError**   0          15s
jmeter-slaves-57cc6b9cfc-5g44x     1/1       Running                      0          15s
jmeter-slaves-57cc6b9cfc-q6j5b     1/1       Running                      0          15s

**Comment by arashkaffamanesh** [comment]
this issue has been solved
