### ISSUE TITLE
Grafana Link not working/ Containers are timing out while trying to ping them from local

### ISSUE THREAD

**Issue by Kapish1122** [kubernauts/jmeter-kubernetes#21]
HI,
So looks like all the steps are working for me. I wanted to know which ip/link should i use for accessing Grafana. Also, i have minkube installed but i want the grafana to be accessible to any user who wants to run a test. It would be great if you could answer these questions for me. Really appreciate your help. Thanks!!

1. My assumption is that every user who wants to run a test should clone the repo and add the 
 test script in there? Is that correct?
2. Currently i have done this entire setup on my local with minikube but the same can be replicated with kubernetes running on the cloud?
3. Grafana link for jmeter service is accessible to all users or any kind of set up needs to be done for any user? The idea is to get the cluster running and folks can just come in and execute the test by starting the ./start_test.sh (once i have initialized the cluster then they should not have to repeat this).
Lastly, my original question regarding the grafana link. Below is the output . Could you guide me as to how i can access grafana via the jmeter service?

s-MacBook-Air:jmeter-operator $ ./initialize_cluster.sh
Enter the Jmeter Namespace: tqa
Creating Influxdb jmeter Database
Creating the Influxdb data source
{"datasource":{"id":1,"orgId":1,"name":"jmeterdb","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://tqa-loadtest-influxdb:8086","password":"admin","user":"admin","database":"jmeter","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"jmeterdb"}s-MacBook-Air:jmeter-operator $ kubectl -n tqa get all
NAME READY STATUS RESTARTS AGE
pod/tqa-loadtest-grafana-7b8db9bdb5-v2rr4 1/1 Running 0 39m
pod/tqa-loadtest-influxdb-745b76b6d6-r6c49 1/1 Running 0 39m
pod/tqa-loadtest-jmeter-master-6cd6d7df46-4mm84 1/1 Running 0 40m
pod/tqa-loadtest-jmeter-slaves-768d8c4dc9-gj9 1/1 Running 0 39m
pod/tqa-loadtest-jmeter-slaves-768d8c4dc9-pbnhl 1/1 Running 0 39m

NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
service/tqa-loadtest-grafana LoadBalancer 10.102.185.69 3000:31762/TCP 39m
service/tqa-loadtest-influxdb ClusterIP 10.96.154.198 8083/TCP,8086/TCP,2003/TCP 39m
service/tqa-loadtest-jmeter-slaves-svc ClusterIP None 1099/TCP,50000/TCP 39m

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/tqa-loadtest-grafana 1/1 1 1 39m
deployment.apps/tqa-loadtest-influxdb 1/1 1 1 39m
deployment.apps/tqa-loadtest-jmeter-master 1/1 1 1 40m
deployment.apps/tqa-loadtest-jmeter-slaves 2/2 2 2 39m

NAME DESIRED CURRENT READY AGE
replicaset.apps/tqa-loadtest-grafana-7b8db9bdb5 1 1 1 39m
replicaset.apps/tqa-loadtest-influxdb-745b76b6d6 1 1 1 39m
replicaset.apps/tqa-loadtest-jmeter-master-6cd6d7df46 1 1 1 40m
replicaset.apps/tqa-loadtest-jmeter-slaves-768d8c4dc9 2

Looks like i dont have the grafana peice working as expected:
kubectl delete svc jmeter-grafana
Error from server (NotFound): services "jmeter-grafana" not found
s-MacBook-Air:jmeter-kubernetes asasd$ kubectl expose deployment jmeter-grafana --port=3000 --external-ip=$192.168.99.100 --type=NodePort
Error from server (NotFound): deployments.extensions "jmeter-grafana" not found

Trying to ping influx/grafana container is timing out from my local but containers are running:
ping 172.17.0.15
PING 172.17.0.15 (172.17.0.15): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

--- 172.17.0.15 ping statistics ---
9 packets transmitted, 0 packets received, 100.0% packet loss
s-MacBook-Air:jmeter-kubernetes asdasd$ ping 172.17.0.14
PING 172.17.0.14 (172.17.0.14): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

**Comment by arashkaffamanesh** [comment]
jmeter-operator? closed.
