### ISSUE TITLE
Error: Missing argument to option -R

### ISSUE THREAD

**Issue by KennethNagin** [kubernauts/jmeter-kubernetes#23]
I'm getting the error message "Error: Missing argument to option -R".
I'm using the "jmeter-kubernetes" to create a workload, i.e. WordPress client, and am collecting metrics on how the workload performs under various network stresses.
I'm running iperf3 to create network stress on the same host as the WordPress server.
When I set the iperf3 -w parameter to 1m I'm getting the error message "Error: Missing argument to option -R".   Any ideas about the cause?  What changes to start_test.sh to get more information?

**Comment by arashkaffamanesh** [comment]
issue too old, closed due inactivity.
