### ISSUE TITLE
Influxdb Permission denied issue

### ISSUE THREAD

**Issue by ImSanjayChintha** [kubernauts/jmeter-kubernetes#34]
I have been trying to connect influxdb via kubernetes pod, its throwing me permissions denied messages like below:

I have no name!@influxdb-jmeter-645d9db66-qdzvd:/$ influx -username admin -password admin
Connected to http://localhost:8086 version 1.8.3
InfluxDB shell version: 1.8.3
> use jmeter
Using database jmeter
There was an error writing history file: open /.influx_history: permission denied
>

**Comment by xykong** [comment]
> I have been trying to connect influxdb via kubernetes pod, its throwing me permissions denied messages like below:
> 
> I have no name!@influxdb-jmeter-645d9db66-qdzvd:/$ influx -username admin -password admin
> Connected to http://localhost:8086 version 1.8.3
> InfluxDB shell version: 1.8.3
> 
> > use jmeter
> > Using database jmeter
> > There was an error writing history file: open /.influx_history: permission denied

I connect to influxdb successfully without given username or password. just try

➜  jmeter-kubernetes git:(master) ✗ influx
Connected to http://localhost:8086 version 1.8.1
InfluxDB shell version: 1.8.2

**Comment by ImSanjayChintha** [comment]
I have tried same. It storing the measurements but throwing the error. However, It is not stopping me to store the data. Hence closing the issue.
