### ISSUE TITLE
Nothing displayed when I run a basic http test

### ISSUE THREAD

**Issue by bfleming-ciena** [kubernauts/jmeter-kubernetes#5]
The app name in the grafana dashboard says None. Just FYI.

**Comment by nysthee** [comment]
I have the same issue.

**Comment by vishal-yadav** [comment]
I am also facing the above issue. Followed steps in the [medium article](https://blog.kubernauts.io/load-testing-as-a-service-with-jmeter-on-kubernetes-fc5288bb0c8b). After importing the GrafanaJmeterTemplate.json able to see the Jmeter Metric Template however stats are not updated when I run the load test. 

@arashkaffamanesh @infinitydon any suggestion?
Also do you know how to access the built-in HTML reports, dashboard.

**Comment by infinitydon** [comment]
Please check the date/time range on the dashboard, change it to something like "last 1 hour"..

![image](https://user-images.githubusercontent.com/6318992/53693671-12273100-3da4-11e9-9a56-44bb66e314dd.png)

I will try to update the grafana dashboard template to use a better default date/time range selection.

As per the built-in HTML report, I believe you are referring to the following documentation?

**_https://jmeter.apache.org/usermanual/generating-dashboard.html_**

I have not used the feature before but you can always access the Jmeter master POD to further customize how you run your test cases.

**Comment by asc-adean** [comment]
I installed this today and I'm seeing the same behavior, blank graphs in the dashboard, regardless of time frame.  It appears that no data is getting into the Influx DB after I ran some light tests.  Connection to the Influx DB appears to be good from Grafana's end.

Here's my `start_test.sh`

```
./start_test.sh RedisAPI.jmx
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/jmeter/apache-jmeter-5.0/lib/log4j-slf4j-impl-2.11.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/jmeter/apache-jmeter-5.0/lib/ext/pepper-box-1.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Creating summariser <summary>
Created the tree successfully using RedisAPI.jmx
Configuring remote engine: 10.110.16.12
Starting remote engines
Starting the test @ Thu Mar 28 20:51:42 UTC 2019 (1553806302887)
Remote engines have been started
Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445
summary +      2 in 00:00:20 =    0.1/s Avg:   982 Min:   950 Max:  1015 Err:     0 (0.00%) Active: 5 Started: 5 Finished: 0
summary +    200 in 00:00:29 =    6.8/s Avg:   967 Min:   947 Max:  1959 Err:     0 (0.00%) Active: 0 Started: 5 Finished: 5
summary =    202 in 00:00:49 =    4.1/s Avg:   967 Min:   947 Max:  1959 Err:     0 (0.00%)
summary +     48 in 00:00:00 = 48000.0/s Avg:   952 Min:   947 Max:   970 Err:     0 (0.00%) Active: 0 Started: 5 Finished: 5
summary =    250 in 00:00:49 =    5.1/s Avg:   964 Min:   947 Max:  1959 Err:     0 (0.00%)
Tidying up remote @ Thu Mar 28 20:52:34 UTC 2019 (1553806354003)
... end of run
```

**Comment by infinitydon** [comment]
Can you share how you configured the InfluxDB endpoint in your Jmeter script?

**Comment by arashkaffamanesh** [comment]
issue too old :-)
