### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by erkanerol** [kubernauts/jmeter-kubernetes#9]
Could you please add LICENSE file? I have an open source project idea and I think I can use this repo as a base. I need it. Thanks.

**Comment by arashkaffamanesh** [comment]
Apache 2.0 License added.

**Comment by erkanerol** [comment]
Thanks a lot!

**Comment by arashkaffamanesh** [comment]
Welcome! Nice to know, that other open source projects could use this implementation as a base.
